<!DOCTYPE html>
<html lang="en-US" ng-app="Site">
<head>
	<meta charset="UTF-8">
	<title>gitFlick</title>
	
<!--<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap.min.css" rel="stylesheet">-->
	<link rel="stylesheet" href="/join_files/css/bootstrap.min.css" />
	<link rel="stylesheet" href="/join_files/css/style2.css" /> 
	<style type="text/css">
  		body {
  		  padding-top:60px;
  		}
  	</style>
</head>

<body>

