<div class="row-fluid">
	<header class="span12 hero-unit effect8" style="background:#fff">
		<div class="row-fluid">
			<p class="shadow grey2" id ="pgraphic" style="text-align:center; letter-spacing:-0.01em; line-height:1">An educational application for FullSail University made by Greg Mitchell. Flickr Api to pull images from flickr.com<img class="pull-right" src="/searchandflick/CodeIgniter/join_files/images/join.png" alt="Sign or Register" /></p>
    			<div class="span12" style="margin-left:-0.2em; background:#fff;">
					<div class="span5 offset4">
						<img class="effect8" src="/searchandflick/CodeIgniter/join_files/images/sf.png" alt="Search and flick" style="margin-top:1em; margin-left:2.2em;" />
							<h1>Search and Flick</h1>
					</div>
				</div>
		</div>
	</header>
</div>