<div class="row-fluid">
	<header class="span12 hero-unit effect8" style="background:#fff">
		<div class="row-fluid">
			<p class="shadow grey2" id ="pgraphic" style="text-align:center; letter-spacing:-0.01em; line-height:1">An educational application for FullSail University made by Greg Mitchell. Flickr Api to pull images from flickr.com</p>
    			<div class="span12" style="margin-left:-0.2em; background:#fff;">
    				<div class="span6 offset3 well">
						<img class="effect8" id="sandf" src="/searchandflick/CodeIgniter/join_files/images/sf.png" alt="Search and flick" style="margin-top:1em; margin-left:6.2em;" />
								<legend style="text-align:center">New to Search and Flick? Sign up!</legend>
								<form accept-charset="UTF-8" action="" method="post">
								<input class="span4" name="name" placeholder="Full Name" type="text">
								<input class="span4" name="username" placeholder="Username" type="text">
								<input class="span4" name="password" placeholder="Password" type="password">
								<button id="join_btn" style="margin-bottom:0.9em; position:relative;" class="btn btn-primary" type="submit">Sign up for S&F</button>
								</form>
								</div>
					</div>
				</div>
		</div>
	</header>
</div>