<div class="row-fluid" id="first_row">
	<header class="span12 hero-unit effect8" id="header_class">
		<div class="row-fluid" id="row-fluid2">
			<p class="shadow grey2" id="pstyle">An educational application for FullSail University made by Greg Mitchell. Flickr Api to pull images from flickr.com</p>
			<div class="span12" id="s12top">
    			<div class="span4 offset4 well">
					<img id="sflogo" class="effect8" id="sandf" src="/searchandflick/CodeIgniter/join_files/images/sf.png" alt="Search and flick" />
						<legend style="text-align:center">New to Search and Flick? Sign up!</legend>
							<form accept-charset="UTF-8" action="" method="post">
								<input class="span4" name="name" placeholder="Full Name" type="text">
								<input class="span4" name="username" placeholder="Username" type="text">
								<input class="span4" name="password" placeholder="Password" type="password">
								<input class="btn btn-primary btn-block three" type="submit" id="join_btn" value="Join SearchandFlick Today" />
							</form>
				</div> <!-- end span4 offset 3 -->
			</div> <!-- end row-fluid -->
		</div> <!-- end row-fluid2 -->
	</header> <!-- end header -->
</div> <!-- end first row  -->