    <div class="row-fluid">
        <header class="span12 hero-unit">
            <h1>Search and Flick</h1>
			<img class="pull-left" src="images/sf.png" alt="Search and Flick"/>
            <p>The easy fun way to browse flicker without actually being there.</p>
        </header>
    </div>
<div class="row-fluid">

</div>
    <ul class="thumbnails">
        <li class="span4">
            <article class="thumbnail">
                <img src="images/ferrar.jpg" alt="Ferrar" />
                <h3>Jonathan Ferrar</h3>
                <p>Labeled as "The Artist to Watch in 2012" by the London Review, Jonathan Ferrar has already sold one of the highest priced-commissions on record paid to an art student.</p>
            </article>
        </li>
        <li class="span4">
            <article class="thumbnail">
                <img src="images/jerome.jpg" alt="jerome" />
                <h3>Jennifer Jerome</h3>
                <p>A native of New Orleans, much of Jennifer Jerome's work has centered around abstract images that depict flooding and rebuilding, having grown up as a teenager in the post-flood years.</p>
            </article>
        </li>
        <li class="span4">
            <article class="thumbnail">
                <img src="images/larue.jpg" alt="Ferrar" />
                <h3>LaVonne LaRue</h3>
                <p>LaVonne LaRue's giant-sized paintings all around Chicago tell the story of love, nature, and conservation - themes that are central to her heart.</p>
            </article>
        </li>
    </ul>

</div>