<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width= device-width, initial-scale=1, maximum-scale=1">
<link href="/searchandflick/join_files/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/searchandflick/join_files/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css">
<link href="/searchandflick/join_files/css/addons.css" rel="stylesheet" type="text/css">
<!-- HTML5 shim for IE backwards compatibility -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<title>Working with Bootstrap</title>
</head>
<body id="signupheader">
<div class="navbar navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</a>
			<a class="brand" href="login" name="top">Search and Flick</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><a href="login"><i class="icon-home"></i> Home</a></li>
						<li class="divider-vertical"></li>
						<li><a href="login"><i class="icon-home"></i> Sign-in</a></li>
						<li class="divider-vertical"></li>
					</ul>
				</div> <!-- end nav collapse -->
		</div> <!-- end fluid container -->
	</div> <!-- end navbar-innder -->
</div> <!-- end navbar -->
<div class="container-fluid">